# Generated by Django 5.2.8 on 2025-12-02 22:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('techniques', 'Techniki'), ('forms', 'Formy (Tul)'), ('terminology', 'Terminologia koreańska'), ('theory', 'Teoria'), ('history', 'Historia'), ('patterns', 'Wzorce ruchów')], max_length=50, verbose_name='Kategoria')),
                ('question', models.TextField(verbose_name='Pytanie/Termin')),
                ('answer', models.TextField(verbose_name='Odpowiedź/Definicja')),
                ('difficulty', models.IntegerField(choices=[(1, 'Podstawowy'), (2, 'Średniozaawansowany'), (3, 'Zaawansowany')], default=2, verbose_name='Poziom trudności')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('is_public', models.BooleanField(default=True, verbose_name='Publiczna')),
                ('views_count', models.IntegerField(default=0, verbose_name='Liczba wyświetleń')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez')),
            ],
            options={
                'verbose_name': 'Fiszka',
                'verbose_name_plural': 'Fiszki',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('category', models.CharField(choices=[('techniques', 'Techniki'), ('forms', 'Formy (Tul)'), ('terminology', 'Terminologia koreańska'), ('theory', 'Teoria'), ('history', 'Historia'), ('patterns', 'Wzorce ruchów')], max_length=50, verbose_name='Kategoria')),
                ('time_limit', models.IntegerField(default=15, verbose_name='Limit czasu (minuty)')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Min. wynik do zaliczenia (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Liczba prób')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Wynik')),
                ('total_questions', models.IntegerField(verbose_name='Liczba pytań')),
                ('percentage', models.FloatField(verbose_name='Procent')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Rozpoczęty')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zakończony')),
                ('passed', models.BooleanField(default=False, verbose_name='Zaliczony')),
                ('time_taken', models.IntegerField(blank=True, null=True, verbose_name='Czas (sekundy)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Próba quizu',
                'verbose_name_plural': 'Próby quizów',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Treść pytania')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('points', models.IntegerField(default=1, verbose_name='Punkty')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Pytanie quizu',
                'verbose_name_plural': 'Pytania quizu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='Treść odpowiedzi')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Poprawna odpowiedź')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training.quizquestion', verbose_name='Pytanie')),
            ],
            options={
                'verbose_name': 'Odpowiedź',
                'verbose_name_plural': 'Odpowiedzi',
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], verbose_name='Dzień tygodnia')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(verbose_name='Godzina zakończenia')),
                ('location', models.CharField(max_length=200, verbose_name='Lokalizacja')),
                ('max_participants', models.IntegerField(default=30, verbose_name='Max uczestników')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Instruktor')),
            ],
            options={
                'verbose_name': 'Dzień treningowy',
                'verbose_name_plural': 'Dni treningowe',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_level', models.CharField(choices=[('white', 'Biały'), ('yellow', 'Żółty'), ('green', 'Zielony'), ('blue', 'Niebieski'), ('red', 'Czerwony'), ('black_1', 'Czarny I Dan'), ('black_2', 'Czarny II Dan'), ('black_3', 'Czarny III Dan')], default='white', max_length=20, verbose_name='Stopień pasa')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Kontakt awaryjny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data rejestracji')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('present', models.BooleanField(default=True, verbose_name='Obecny')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Dodane przez')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingday', verbose_name='Dzień treningowy')),
            ],
            options={
                'verbose_name': 'Obecność',
                'verbose_name_plural': 'Obecności',
                'ordering': ['-date', 'user__username'],
                'unique_together': {('user', 'training_day', 'date')},
            },
        ),
    ]
