# Generated by Django 5.2.9 on 2025-12-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_level', models.CharField(choices=[('yellow_white', 'Biało-żółty'), ('yellow', 'Żółty'), ('green_yellow', 'Żółto-zielony'), ('green', 'Zielony'), ('blue_green', 'Zielono-niebieski'), ('blue', 'Niebieski'), ('red_blue', 'Niebiesko-czerwony'), ('red', 'Czerwony'), ('black_red', 'Czerwono-czarny'), ('black_1', 'I Dan'), ('black_2', 'II Dan'), ('black_3', 'III Dan'), ('black_4', 'IV Dan'), ('black_5', 'V Dan'), ('black_6', 'VI Dan'), ('black_7', 'VII Dan'), ('black_8', 'VIII Dan'), ('black_9', 'IX Dan')], max_length=20, verbose_name='Stopień')),
                ('date', models.DateField(verbose_name='Data egzaminu')),
                ('time', models.TimeField(verbose_name='Godzina')),
                ('location', models.CharField(max_length=200, verbose_name='Miejsce')),
                ('examiner', models.CharField(blank=True, max_length=200, verbose_name='Egzaminator')),
                ('max_participants', models.IntegerField(default=20, verbose_name='Maksymalna liczba uczestników')),
                ('description', models.TextField(blank=True, verbose_name='Opis/Wymagania')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egzamin',
                'verbose_name_plural': 'Egzaminy',
                'ordering': ['date', 'time'],
            },
        ),
    ]
