# Generated by Django 5.2.9 on 2025-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Wymagana zmiana hasła'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hasło tymczasowe'),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek')], verbose_name='Dzień tygodnia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='belt_level',
            field=models.CharField(choices=[('white', 'Biały'), ('yellow_white', 'Biało-żółty'), ('yellow', 'Żółty'), ('green_yellow', 'Żółto-zielony'), ('green', 'Zielony'), ('blue_green', 'Zielono-niebieski'), ('blue', 'Niebieski'), ('red_blue', 'Niebiesko-czerwony'), ('red', 'Czerwony'), ('black_red', 'Czerwono-czarny'), ('black_1', 'I Dan'), ('black_2', 'II Dan'), ('black_3', 'III Dan'), ('black_4', 'IV Dan'), ('black_5', 'V Dan'), ('black_6', 'VI Dan'), ('black_7', 'VII Dan'), ('black_8', 'VIII Dan'), ('black_9', 'IX Dan')], default='white', max_length=20, verbose_name='Stopień pasa'),
        ),
    ]
