# Generated by Django 5.2.9 on 2025-12-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='group',
            field=models.CharField(choices=[('white', 'Grupa Biały pas (10-9 kup)'), ('yellow', 'Grupa Żółty pas (8-7 kup)'), ('green', 'Grupa Zielony pas (6-5 kup)'), ('blue', 'Grupa Niebieski pas (4-3 kup)'), ('red', 'Grupa Czerwony pas (2-1 kup)'), ('black', 'Grupa Czarny pas (Dan)')], default='white', max_length=20, verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hasło tymczasowe'),
        ),
    ]
