# Generated by Django 5.2.9 on 2025-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_flashcard_difficulty_flashcard_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Jednokrotnego wyboru'), ('multiple', 'Wielokrotnego wyboru'), ('text', 'Odpowiedź opisowa')], default='single', max_length=20, verbose_name='Typ pytania'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Oczekiwana odpowiedź (dla pytań opisowych)'),
        ),
    ]
