# Generated by Django 5.2.9 on 2025-12-10 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_quizquestion_question_type_quizquestion_text_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Próba quizu', 'verbose_name_plural': 'Próby quizu'},
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='time_taken',
        ),
        migrations.CreateModel(
            name='PrivateLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(verbose_name='Godzina zakończenia')),
                ('status', models.CharField(choices=[('available', 'Dostępne'), ('booked', 'Zarezerwowane'), ('completed', 'Zakończone'), ('cancelled', 'Anulowane')], default='available', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Instruktor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Uczeń')),
            ],
            options={
                'verbose_name': 'Zajęcia indywidualne',
                'verbose_name_plural': 'Zajęcia indywidualne',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
