# Generated by Django 5.2.9 on 2025-12-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='belt_level',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('color_belts', 'Pasy kolorowe (biało-żółty do czerwony)'), ('advanced_belts', 'Stopnie wyższe (czerwono-czarny do V Dan)')], default='color_belts', max_length=20, verbose_name='Typ egzaminu'),
        ),
    ]
