# Generated by Django 5.2.9 on 2025-12-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_exam_belt_level_exam_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Poprawna')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='training.quizattempt', verbose_name='Próba')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.quizquestion', verbose_name='Pytanie')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.quizanswer', verbose_name='Wybrana odpowiedź')),
            ],
            options={
                'verbose_name': 'Odpowiedź użytkownika',
                'verbose_name_plural': 'Odpowiedzi użytkowników',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
